"""Phase 4 acceptance (scripted end-to-end, no spend):
- nightly journals with credences are produced
- >=90% of evidence citations resolve to real observation ids (plumbing)
- in a C1 world the scripted investigator catches real seams (verdict scorer
  classifies claims true_seam) and the funnel reaches stage 4 (attributed)
- in a clean world the same investigator reports nothing (heuristic baseline)
- the investigator's sealed note is genuine state: never a contradiction
- formatting audit: provenance not classifiable from packet form
"""
import json
from pathlib import Path

from engine.engine import Runner
from referee.leak_detector import detect
from referee.verdict import score

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
from format_audit import audit  # noqa: E402

BASE = {
    "seed": 5,
    "days": 2,
    "villagers": ["Mara Quill", "Edith Bramble", "Sam Alder",
                  "Petra Lowell", "Descartes Vane"],
    "llm": {"mode": "scripted"},
    "doc_read_chance": 0.25,
    "investigator": {"agent": "Descartes Vane", "variant": "primed",
                     "action_every_ticks": 2},
}

C1 = {"o1_lazy": True, "o2_history": True, "o3_cache": "naive", "generator": "procedural"}
C2 = {"o1_lazy": True, "o2_history": True, "o3_cache": "cached", "generator": "procedural"}


def _run(tmp_path, name, optimisations=None):
    config = dict(BASE)
    if optimisations:
        config["optimisations"] = optimisations
    out = tmp_path / name
    Runner(config, out).run()
    return out


def test_investigator_in_c1_catches_seams(tmp_path):
    out = _run(tmp_path, "c1", C1)

    # journals exist with credences
    journals = sorted((out / "journals").glob("day*.json"))
    assert len(journals) == 2
    days = [json.loads(j.read_text()) for j in journals]
    assert all(isinstance(d["credence"], int) for d in days)

    v = score(out)
    assert v["journals"] == 2
    assert v["claims_flagged"] >= 1
    # plumbing acceptance: citations resolve
    assert v["citation_resolution_rate"] is not None
    assert v["citation_resolution_rate"] >= 0.9
    # the scripted investigator's reread test catches real seams
    assert v["class_counts"].get("true_seam", 0) >= 1
    # funnel stage 4: citations cover both sides of a contradiction
    assert v["claims_attributed"] >= 1
    # credence rises once evidence lands
    assert v["final_credence"] > days[0]["credence"] or days[0]["credence"] > 15

    # the sealed note is genuine state: no contradiction on its fact key
    report = detect(out)
    note_keys = [c for c in report["contradictions"]
                 if c["fact_key"].startswith("doc:note_")]
    assert not note_keys
    # the note was actually left and checked
    log = [json.loads(l) for l in (out / "god_log.jsonl").read_text().splitlines()]
    assert any(e["event_type"] == "world_change"
               and e["fact_key"].startswith("doc:note_") for e in log)


def test_investigator_in_clean_world_reports_nothing(tmp_path):
    out = _run(tmp_path, "clean")
    v = score(out)
    assert v["journals"] == 2
    assert v["class_counts"].get("true_seam", 0) == 0
    # scripted heuristic doesn't confabulate: clean world -> no claims at all
    assert v["claims_flagged"] == 0
    assert all(t["credence"] <= 15 for t in v["credence_trajectory"])


def test_interviews_touch_history_store_under_o2(tmp_path):
    out = _run(tmp_path, "hist", C1)
    log = [json.loads(l) for l in (out / "god_log.jsonl").read_text().splitlines()]
    hist_gens = [e for e in log if e["event_type"] == "generation"
                 and e["fact_key"].startswith("history:")]
    assert hist_gens, "no on-demand history was generated by interviews"
    interviews = [e for e in log if e["event_type"] == "observation"
                  and e["focus"].startswith("interview:")]
    assert interviews


def test_format_audit_passes_on_c2(tmp_path):
    out = _run(tmp_path, "c2", C2)
    result = audit([out])
    assert result["pass"], result
    # both eager-ish and generated content present so the check is non-vacuous
    assert result.get("classes", {}).get("generated", 0) > 0


def test_llm_path_survives_unparseable_outputs(tmp_path):
    # mock LLM returns non-JSON for actions/journals; investigator must fall
    # back to observe and record a parse_error journal rather than crash
    config = dict(BASE, ticks=64, llm={"mode": "mock"},
                  budget={"cap_usd": 5.0})
    out = tmp_path / "mock"
    Runner(config, out).run()
    j = json.loads((out / "journals" / "day1.json").read_text())
    assert j["parse_error"] is True and j["credence"] is None